### ISSUE TITLE
求助，关于tracker_traffic_null表的一些问题

### ISSUE THREAD

**Issue by zunsthy** [QingyingPT/QY-PT-tracker#2]
`tracker_traffic_null` 表用来存储的是没有产生流量的做种/下载信息，
https://github.com/QingyingPT/QY-PT-tracker/blob/develop/announce.php#L428
```php
  $fields = [
    'torrent',
    'userid',
    'peer_id',
    'port',
    'during',
    'seeder',
  ];
  $values = [
    $torrent['id'],
    $user['id'],
    $peerid,
    $info['port'],
    $timeTraffic,
    $seeder,
  ];
  $sqlLink->query("INSERT INTO tracker_traffic_null (" .join(',', $fields) .") VALUES ('" .join("','", $values) ."')")
```
表结构如下
```sql
CREATE TABLE `tracker_traffic_null` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `torrent` int(10) unsigned NOT NULL DEFAULT '0',
  `userid` int(10) unsigned NOT NULL DEFAULT '0',
  `peer_id` binary(20) NOT NULL,
  `port` smallint(5) unsigned NOT NULL DEFAULT '0',
  `during` int(10) unsigned NOT NULL DEFAULT '0',
  `seeder` boolean NOT NULL DEFAULT false,
  `last_action` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `is_old` boolean NOT NULL DEFAULT false,
) ENGINE=InnoDB;
```
测试开放了一天，平均每次更新时有 500 个 peer，announce 间隔时间设置了 1200 秒，表大小就从 0 增长到了 16MB。
清影正常时平均 20000 个 peer，按照这个速度，一个月就会产生 15GB 数据。
这样下去肯定是不行的，**求助支援一个可行的解决方案**。

**Comment by Fairly** [comment]
不太清楚这个表是做什么的。这里面的数据是都要永久保存的吗？需要一直在线吗？隔一段时间做个压缩归档可以吗？

**Comment by zunsthy** [comment]
@Fairly 這個表記錄的是做種時間，一方面用來計算H&R，一方面用來檢查是否作弊。
設計之初的想法是保留半年的，但是這增長速度太快，超過預期，一個月的數據都存不下。所以得考慮下怎麼備份，還有就是在想查歷史的時候快速查到歷史數據。

想了想，你說的這個是個辦法，數據其實可以不存在服務器上，離線做處理也是可以的，具體我再考慮下。

**Comment by ppoffice** [comment]
@zunsthy 产生了多少数据呢？

**Comment by zunsthy** [comment]
@ppoffice 5天，231180行。

**Comment by ppoffice** [comment]
@zunsthy 我看了下，对于同一用户、同一种子，表中记录主要变化的字段为`during`和`last_action`。可不可以对连续的记录进行合并，例如：

| during | last_action |
| --- |:---:|
| 600 | 2017-04-23 21:02:00 |
| 1200 | 2017-04-23 21:22:00 |

可不可以合并成：

| during | last_action |
| --- |:---:|
| 1800 | 2017-04-23 21:22:00 |

如果其他地方要对last_action按时间段进行筛选的话，我觉着更好的存储方式是存储起止时间：

| prev_action | last_action |
|:---:|:---:|
| 2017-04-23 20:52:00 | 2017-04-23 21:22:00 |

**Comment by zunsthy** [comment]
@ppoffice 设计这个表最初的想法是直接把做种时间和激励点数关联起来，比如做种7天，可以抵消10G的下载量。

合并这个方法不错，但是这个表之后可能还要再加上"这个时间内的种子状态"这个字段，作为权重计算获得的激励点数，这样就不好合并了。

`during`的想法是用来统计做种时间，可以直接用sum来算，算过的条目过上一段时间之后直接抛弃就好，留下来意义不大。

起止时间这个我回去试试看，感觉很不错的样子（在`tracker_traffic`这张表里面似乎更有用）。

还有个问题，`datetime`和`int`用哪个更好 :3

**Comment by ppoffice** [comment]
@zunsthy datetime 8字节，timestamp四个字节，int长度就看自己定义了

**Comment by zunsthy** [comment]
@ppoffice 
~~datetime是int(14)，int是int(12)，timestamp是64位，讀速度上datetime和int差不多，寫速度慢了很多，似乎是因為做有效校驗的原因。~~

我理解错了，面壁反思中。

這個表大小增長似乎不是線性的，數據多了十倍，體積卻沒有大那麼多……
