### ISSUE TITLE
切换网络后种子状态变为wait 30 minutes.

### ISSUE THREAD

**Issue by yumendy** [QingyingPT/QY-PT-tracker#3]
开始下载的时候没注意用的是学校的hit-wlan速度不佳，想用有线快一点，于是关闭了ut，切换完网络之后再打开ut种子状态就变为了please wait 30 minutes。
不知道这个是不是反作弊机制，但是现在似乎这样的使用场景挺容易发生的，30min的话会不会有点太长了。

**Comment by zunsthy** [comment]
@yumendy 
如果是先停止再切換就不會了。（原來的話會提示 You download the same torrent in the time, please wait for 30 min

https://github.com/QingyingPT/QY-PT-tracker/blob/develop/announce.php#L222-L223
```javascript
if ($num > 0 && !$seeder)
  Notice('Please wait 30 minutes.');
```
這裡做了一次判斷，如果同時在多個地方下載，就直接報錯。

感覺可以在網站增加一個清除冗餘 peer 的功能。

**Comment by zunsthy** [comment]
（剛剛試了下，直接切換就行，似乎不用關閉uT
